spring.application.name=gym-tracker

server.port=8093

spring.datasource.url=jdbc:postgresql://localhost:5432/gym-tracker
spring.datasource.username=postgres
spring.datasource.password=postgres
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



# Configuração para criação automática das tabelas
#spring.jpa.hibernate.ddl-auto=update

# Configuração para criar as tabelas a cada execução (usar quando mudar o modelo das relações)
spring.jpa.hibernate.ddl-auto=create-drop

# Opcional: mostrar as consultas SQL no console
spring.jpa.show-sql=true

# Opcional: formatar o SQL para melhor leitura
spring.jpa.properties.hibernate.format_sql=true